services:
  api:
    build:
      context: .
      dockerfile: Dockerfile
    env_file:
      - .env
    volumes:
      - ./src:/app/src
    ports:
      - ${API_PORT}:${API_PORT}
    depends_on:
      - db

  db:
    container_name: db
    image: postgres:latest
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_USER=docker
      - POSTGRES_PASSWORD=docker
      - POSTGRES_DB=eventix_db
    volumes:
      - db_data:/var/lib/postgresql/data
volumes:
  db_data:
